In [1]:
import numpy as np
import tensorflow as tf

2022-11-11 06:38:24.330373: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-11 06:38:24.417069: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-11 06:38:24.817007: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-11-11 06:38:24.817046: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or 

In [3]:
from tensorflow import nn
from tensorflow.keras import layers

# Single-Channel Input

In [109]:
# create dummy input that's easy to debug
input_tensor = tf.convert_to_tensor(np.matrix('''
    3 3 2 1 0;
    0 0 1 3 1;
    3 1 2 2 3;
    2 0 0 2 2;
    2 0 0 0 1
'''), dtype=tf.float32)
input_tensor = tf.expand_dims(input_tensor, 0)
input_tensor = tf.expand_dims(input_tensor, -1)
input_tensor.shape

TensorShape([1, 5, 5, 1])

Each 3x3 block has a set of 1s applied to it and summed for the output

In [91]:
c2d = layers.Conv2D(1, kernel_size=(3, 3,), activation=None, kernel_initializer='ones') # a 3x3 of all 1s
c2d(input_tensor, )

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[15.],
         [15.],
         [15.]],

        [[ 9.],
         [11.],
         [16.]],

        [[10.],
         [ 7.],
         [12.]]]], dtype=float32)>

What are strides?

In [92]:
# same as above EXCEPT for the strides
c2d = layers.Conv2D(1, kernel_size=(3, 3,), strides=2, activation=None, kernel_initializer='ones') # a 3x3 of all 1s
c2d(input_tensor, ) # kernel skips 2 instead of 1

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[15.],
         [15.]],

        [[10.],
         [12.]]]], dtype=float32)>

- Strides control how many cells to slide across
- kernel size controls how far/how many cells to sum from 

# Multi-Channel Input

In [136]:
input_tensor = np.random.choice([0, 1, 2], size=(2, 5, 5))
input_tensor = tf.convert_to_tensor(input_tensor, dtype=tf.float32)
input_tensor = tf.expand_dims(input_tensor, 0)

input_tensor.shape

TensorShape([1, 2, 5, 5])

In [137]:
input_tensor

<tf.Tensor: shape=(1, 2, 5, 5), dtype=float32, numpy=
array([[[[1., 0., 1., 1., 2.],
         [1., 0., 0., 2., 2.],
         [1., 2., 2., 0., 0.],
         [0., 0., 2., 2., 0.],
         [1., 1., 2., 2., 2.]],

        [[2., 2., 2., 2., 0.],
         [1., 1., 0., 0., 2.],
         [2., 0., 2., 0., 1.],
         [2., 1., 1., 1., 1.],
         [0., 0., 0., 0., 2.]]]], dtype=float32)>

In [138]:
input_tensor = tf.reshape(input_tensor, shape=(1, 5, 5, 2))

In [141]:

c2d = layers.Conv2D(1, kernel_size=(1, 1),activation=None, kernel_initializer='ones') # a 3x3 of all 1s
tf.squeeze(c2d(input_tensor)) # squeeze removes batch dimension

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 2., 3., 0., 4.],
       [3., 2., 0., 2., 2.],
       [2., 4., 4., 4., 2.],
       [2., 0., 4., 2., 1.],
       [3., 2., 1., 0., 2.]], dtype=float32)>

In [8]:
tf.test.is_built_with_cuda(), tf.test.is_gpu_available()


Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


2022-11-11 13:29:45.247597: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


(True, False)

In [7]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))


Num GPUs Available:  0
